USE WIDGET_DEPARTMENT
GO

--Query to show employees by department
SELECT    dbo.EMPLOYEES.EMPLOYEE_NAME, dbo.DEPARTMENT_NAME.DEPARTMENT_NAME, dbo.EMPLOYEES.DEPARTMENT_ID
FROM       dbo.EMPLOYEES INNER JOIN
               dbo.DEPARTMENT_NAME ON dbo.EMPLOYEES.DEPARTMENT_ID = dbo.DEPARTMENT_NAME.DEPARTMENT_ID