USE [WIDGET_DEPARTMENT]
GO
select *
from employees

--ADDS 10%
update EMPLOYEES
SET SALARY =  SALARY + (SALARY * 10)/100
WHERE EMPLOYEE_ID = 90011

-- MINUS 10%
update EMPLOYEES
SET SALARY =  SALARY - (SALARY * 10)/100
WHERE EMPLOYEE_ID = 90011